#SERVICE
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 31001
    name: nginx-np
